version: "3.8"

services:
  fastapi-app:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src/server:/code
    environment:
      - ENV=development
    networks:
      - my_network

  ollama:
    build:
      context: ./src/ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - .:/app/
      - ./ollama:/root/.ollama
    restart: always
    tty: true
    networks:
      - my_network

volumes:
  ollama:
networks:
  my_network:
    driver: bridge
