version: "3.8"

services:
  fastapi-app:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src/server:/code
    environment:
      - ENV=development
    networks:
      - my_network
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    build:
      context: ./src/ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - .:/app/
      - ./ollama:/root/.ollama
    restart: always
    tty: true
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/ollama_ready"]
      interval: 5s
      timeout: 10s
      retries: 99999

volumes:
  ollama:
networks:
  my_network:
    driver: bridge
