name: Run Python Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .src/w3b_sc4ap3/requirements.txt  # Ensure you have a requirements.txt file

    - name: Run tests
      run: |
        python -m unittest discover -s . -p "tests*.py"

